~blackmad/NO_BACKUP/osm/bin/osmosis \
  --read-pbf $1 \
  --tf accept-ways amenity=* \
  --tf accept-ways boundary=* \
  --tf accept-ways building=* \
  --tf accept-ways craft=* \
  --tf accept-ways geological=* \
  --tf accept-ways historic=* \
  --tf accept-ways landuse=* \
  --tf accept-ways leisure=* \
  --tf accept-ways military=* \
  --tf accept-ways natural=* \
  --tf accept-ways office=* \
  --tf accept-ways place=* \
  --tf accept-ways shop=* \
  --tf accept-ways sport=* \
  --tf accept-ways tourism=* \
  --tf accept-ways landmark=* \
  --tf accept-ways monument=* \
  --tf accept-relations amenity=* \
  --tf accept-relations boundary=* \
  --tf accept-relations building=* \
  --tf accept-relations craft=* \
  --tf accept-relations geological=* \
  --tf accept-relations historic=* \
  --tf accept-relations landuse=* \
  --tf accept-relations leisure=* \
  --tf accept-relations military=* \
  --tf accept-relations natural=* \
  --tf accept-relations office=* \
  --tf accept-relations place=* \
  --tf accept-relations shop=* \
  --tf accept-relations sport=* \
  --tf accept-relations tourism=* \
  --tf accept-relations landmark=* \
  --tf accept-relations monument=* \
  --tf reject-relations admin_level=* \
  --tf reject-ways admin_level=* \
  --tf reject-relations boundary=administrative \
  --tf reject-ways boundary=administrative \
  --used-way \
  --used-node \
  --write-pbf other_bounds.osm.pbf
